"""
GPU Cluster Simulator for ThermoCache.

This module simulates a multi-GPU cluster with realistic thermal behavior,
workload patterns, and context sharing scenarios for testing and demonstration.
"""

import random
import logging
from typing import Dict, List, Optional, Tuple
from datetime import datetime
import asyncio

import numpy as np

from models.schemas import GPUMetrics, WorkloadSize, InferenceRequest, SystemMetrics
from context_cache.engine import ContextCache
from thermal.predictor import ThermalPredictor
from scheduler.scheduler import ThermalAwareScheduler, BaselineScheduler


logger = logging.getLogger(__name__)


class SimulatedGPU:
    """
    Simulates a single GPU with thermal dynamics and workload processing.
    """
    
    def __init__(
        self,
        gpu_id: int,
        rack_id: int,
        vram_total: float = 24.0,
        base_temp: float = 45.0,
        cooling_efficiency: float = 1.0
    ):
        """
        Initialize simulated GPU.
        
        Args:
            gpu_id: GPU identifier
            rack_id: Rack identifier
            vram_total: Total VRAM in GB
            base_temp: Base/idle temperature
            cooling_efficiency: Cooling efficiency factor (0.5-1.5)
        """
        self.gpu_id = gpu_id
        self.rack_id = rack_id
        self.vram_total = vram_total
        self.base_temp = base_temp
        self.cooling_efficiency = cooling_efficiency
        
        # Current state
        self.temperature = base_temp
        self.utilization = 0.0
        self.vram_used = 0.0
        self.power_draw = 50.0  # Idle power
        self.contexts: List[str] = []
        self.workload_queue: List[str] = []
        
        # Thermal dynamics parameters
        self.thermal_mass = 10.0  # Higher = slower temp change
        self.load_heating_coefficient = 0.4  # °C per % utilization
        self.ambient_cooling_coefficient = 0.1 * cooling_efficiency
    
    def update_state(
        self,
        new_utilization: float,
        new_vram_used: float,
        contexts: List[str],
        ambient_temp: float = 25.0
    ):
        """
        Update GPU state and simulate thermal dynamics.
        
        Args:
            new_utilization: New utilization percentage
            new_vram_used: New VRAM usage in GB
            contexts: List of context IDs on this GPU
            ambient_temp: Ambient temperature
        """
        self.utilization = max(0, min(100, new_utilization))
        self.vram_used = max(0, min(self.vram_total, new_vram_used))
        self.contexts = contexts
        
        # Calculate power draw (simple model)
        idle_power = 50.0
        max_power = 300.0
        self.power_draw = idle_power + (max_power - idle_power) * (self.utilization / 100)
        
        # Simulate thermal dynamics
        # Heat generated by load
        heat_from_load = self.utilization * self.load_heating_coefficient
        
        # Cooling toward ambient
        cooling = (self.temperature - ambient_temp) * self.ambient_cooling_coefficient
        
        # Temperature change with thermal mass smoothing
        delta_t = (heat_from_load - cooling) / self.thermal_mass
        
        # Add some randomness for realism
        noise = random.gauss(0, 0.3)
        
        self.temperature += delta_t + noise
        
        # Clamp to reasonable range
        self.temperature = max(ambient_temp + 5, min(95, self.temperature))
    
    def get_metrics(self) -> GPUMetrics:
        """Get current metrics as GPUMetrics object."""
        # Calculate thermal trend from recent history
        thermal_trend = random.gauss(0, 0.5)  # Simplified
        
        # Calculate thermal headroom
        max_operating_temp = 85.0
        thermal_headroom = max(0, min(1, (max_operating_temp - self.temperature) / 60))
        
        return GPUMetrics(
            gpu_id=self.gpu_id,
            temperature=self.temperature,
            utilization=self.utilization,
            vram_used=self.vram_used,
            vram_total=self.vram_total,
            power_draw=self.power_draw,
            thermal_trend=thermal_trend,
            thermal_headroom=thermal_headroom,
            memory_pressure=self.vram_used / self.vram_total if self.vram_total > 0 else 0,
            rack_id=self.rack_id,
            contexts=self.contexts.copy()
        )


class GPUClusterSimulator:
    """
    Simulates a complete GPU cluster with multiple racks and GPUs.
    """
    
    def __init__(
        self,
        num_gpus: int = 8,
        num_racks: int = 4,
        vram_per_gpu: float = 24.0
    ):
        """
        Initialize GPU cluster simulator.
        
        Args:
            num_gpus: Number of GPUs to simulate
            num_racks: Number of racks
            vram_per_gpu: VRAM per GPU in GB
        """
        self.num_gpus = num_gpus
        self.num_racks = num_racks
        self.gpus: Dict[int, SimulatedGPU] = {}
        
        # Create GPUs distributed across racks
        gpus_per_rack = num_gpus // num_racks
        gpu_idx = 0
        
        for rack_id in range(num_racks):
            # Vary cooling efficiency by rack (some racks cool better)
            rack_cooling = 0.8 + random.random() * 0.4  # 0.8 to 1.2
            
            for i in range(gpus_per_rack if rack_id < num_racks - 1 else num_gpus - gpu_idx):
                # Vary base temperature slightly
                base_temp = 40 + random.random() * 10
                
                self.gpus[gpu_idx] = SimulatedGPU(
                    gpu_id=gpu_idx,
                    rack_id=rack_id,
                    vram_total=vram_per_gpu,
                    base_temp=base_temp,
                    cooling_efficiency=rack_cooling
                )
                gpu_idx += 1
        
        # Simulation state
        self.request_count = 0
        self.start_time = datetime.now()
    
    def get_all_metrics(self) -> List[GPUMetrics]:
        """Get metrics for all GPUs."""
        return [gpu.get_metrics() for gpu in self.gpus.values()]
    
    def get_gpu_metrics(self, gpu_id: int) -> Optional[GPUMetrics]:
        """Get metrics for specific GPU."""
        if gpu_id in self.gpus:
            return self.gpus[gpu_id].get_metrics()
        return None
    
    def update_gpu_workload(
        self,
        gpu_id: int,
        utilization_delta: float,
        vram_delta: float,
        contexts: Optional[List[str]] = None
    ):
        """
        Update workload on a specific GPU.
        
        Args:
            gpu_id: GPU to update
            utilization_delta: Change in utilization
            vram_delta: Change in VRAM usage
            contexts: New context list (optional)
        """
        if gpu_id not in self.gpus:
            return
        
        gpu = self.gpus[gpu_id]
        current_metrics = gpu.get_metrics()
        
        new_util = current_metrics.utilization + utilization_delta
        new_vram = current_metrics.vram_used + vram_delta
        
        if contexts is None:
            contexts = current_metrics.contexts
        
        gpu.update_state(new_util, new_vram, contexts)
    
    def simulate_workload_tick(self, dt_seconds: float = 1.0):
        """
        Advance simulation by one tick.
        
        Args:
            dt_seconds: Time step in seconds
        """
        for gpu in self.gpus.values():
            # Natural cooling when underutilized
            if gpu.utilization < 30:
                gpu.utilization = max(0, gpu.utilization - 2)
            
            # Slight random fluctuations
            gpu.utilization += random.gauss(0, 3)
            gpu.utilization = max(0, min(100, gpu.utilization))
            
            # Update state
            gpu.update_state(
                gpu.utilization,
                gpu.vram_used,
                gpu.contexts
            )
    
    def add_context_to_gpu(self, gpu_id: int, context_id: str, memory_size: float):
        """Add a context to a GPU."""
        if gpu_id in self.gpus:
            if context_id not in self.gpus[gpu_id].contexts:
                self.gpus[gpu_id].contexts.append(context_id)
                self.gpus[gpu_id].vram_used += memory_size
    
    def remove_context_from_gpu(self, gpu_id: int, context_id: str, memory_size: float):
        """Remove a context from a GPU."""
        if gpu_id in self.gpus:
            if context_id in self.gpus[gpu_id].contexts:
                self.gpus[gpu_id].contexts.remove(context_id)
                self.gpus[gpu_id].vram_used = max(0, self.gpus[gpu_id].vram_used - memory_size)
    
    def get_system_metrics(
        self,
        context_cache: Optional[ContextCache] = None
    ) -> SystemMetrics:
        """
        Get aggregated system metrics.
        
        Args:
            context_cache: Optional context cache for hit rate
            
        Returns:
            SystemMetrics object
        """
        metrics_list = self.get_all_metrics()
        
        temps = [m.temperature for m in metrics_list]
        total_vram_used = sum(m.vram_used for m in metrics_list)
        total_vram_capacity = sum(m.vram_total for m in metrics_list)
        total_power = sum(m.power_draw for m in metrics_list)
        
        # Find thermal hotspots (GPUs above warning temp)
        hotspots = [m.gpu_id for m in metrics_list if m.temperature > 75]
        
        # Context stats
        total_contexts = 0
        context_hit_rate = 0.0
        kv_cache_saved = 0.0
        
        if context_cache:
            # Use asyncio.create_task instead of asyncio.run when in event loop
            try:
                loop = asyncio.get_running_loop()
                # We're in an async context, use await directly
                stats_task = asyncio.create_task(context_cache.get_cache_stats())
            except RuntimeError:
                # No running loop, use asyncio.run
                stats = asyncio.run(context_cache.get_cache_stats())
            else:
                # This won't work directly - we need to handle this differently
                # For now, just get basic stats without async
                stats = {
                    "total_contexts": context_cache.index.total_contexts,
                    "hit_rate": context_cache.index.hit_rate,
                    "duplicate_requests": context_cache.duplicate_requests,
                    "saved_contexts": context_cache.saved_contexts,
                    "total_memory_gb": context_cache.index.total_memory_used
                }
            
            if 'stats' not in dir():  # Only if we didn't already get stats
                stats = {
                    "total_contexts": context_cache.index.total_contexts,
                    "hit_rate": context_cache.index.hit_rate,
                    "duplicate_requests": context_cache.duplicate_requests,
                    "saved_contexts": context_cache.saved_contexts,
                    "total_memory_gb": context_cache.index.total_memory_used
                }
            
            total_contexts = stats["total_contexts"]
            context_hit_rate = stats["hit_rate"]
            kv_cache_saved = stats["total_memory_gb"] * stats["duplicate_requests"] / max(1, stats["saved_contexts"])
        
        elapsed = (datetime.now() - self.start_time).total_seconds()
        rps = self.request_count / elapsed if elapsed > 0 else 0
        
        return SystemMetrics(
            total_gpus=self.num_gpus,
            active_gpus=sum(1 for m in metrics_list if m.utilization > 0),
            average_temperature=sum(temps) / len(temps),
            peak_temperature=max(temps),
            total_vram_used=total_vram_used,
            total_vram_capacity=total_vram_capacity,
            vram_utilization_percent=(total_vram_used / total_vram_capacity) * 100 if total_vram_capacity > 0 else 0,
            total_contexts=total_contexts,
            context_hit_rate=context_hit_rate,
            kv_cache_memory_saved=kv_cache_saved,
            requests_per_second=rps,
            average_latency_ms=50 + random.gauss(0, 10),  # Simulated
            estimated_power_kw=total_power / 1000,
            thermal_hotspots=hotspots
        )


class WorkloadGenerator:
    """
    Generates synthetic inference workloads with configurable patterns.
    """
    
    def __init__(
        self,
        context_sharing_ratio: float = 0.7,
        seed: Optional[int] = None
    ):
        """
        Initialize workload generator.
        
        Args:
            context_sharing_ratio: Fraction of requests that share context
            seed: Random seed for reproducibility
        """
        self.context_sharing_ratio = context_sharing_ratio
        self.rng = np.random.default_rng(seed)
        
        # Predefined contexts for sharing
        self.shared_contexts = [
            ("company-handbook", "Company employee handbook with policies and procedures..."),
            ("api-docs", "API documentation for the platform including endpoints..."),
            ("code-base", "Source code repository for the main application..."),
            ("research-paper", "Research paper on transformer architectures..."),
            ("legal-docs", "Legal documents and terms of service..."),
        ]
        
        self.request_counter = 0
    
    def generate_request(self) -> InferenceRequest:
        """Generate a single inference request."""
        self.request_counter += 1
        
        # Decide if this request uses shared context
        use_shared = self.rng.random() < self.context_sharing_ratio
        
        if use_shared:
            ctx_id, ctx_content = self.rng.choice(self.shared_contexts)
        else:
            ctx_id = f"unique-{self.request_counter}"
            ctx_content = f"Unique content for request {self.request_counter}..."
        
        # Generate prompt variations
        prompts = [
            f"Explain the key points in {ctx_id}.",
            f"What does {ctx_id} say about security?",
            f"Summarize {ctx_id}.",
            f"Find information about authentication in {ctx_id}.",
            f"How does {ctx_id} handle errors?",
        ]
        
        prompt = self.rng.choice(prompts)
        
        # Estimate workload size
        size_choice = self.rng.choice(["SMALL", "MEDIUM", "LARGE"], p=[0.5, 0.35, 0.15])
        max_tokens = {"SMALL": 128, "MEDIUM": 512, "LARGE": 2048}[size_choice]
        
        return InferenceRequest(
            request_id=f"req_{self.request_counter:06d}",
            prompt=prompt,
            context=ctx_id,
            max_tokens=max_tokens,
            priority=self.rng.integers(1, 11),
            user_id=f"user_{self.rng.integers(1, 100)}"
        )
    
    def generate_batch(self, count: int) -> List[InferenceRequest]:
        """Generate a batch of requests."""
        return [self.generate_request() for _ in range(count)]


class SimulationRunner:
    """
    Runs comparison simulations between baseline and ThermoCache schedulers.
    """
    
    def __init__(
        self,
        cluster: GPUClusterSimulator,
        context_sharing_ratio: float = 0.7,
        seed: Optional[int] = None
    ):
        """
        Initialize simulation runner.
        
        Args:
            cluster: GPU cluster simulator
            context_sharing_ratio: Context sharing ratio
            seed: Random seed
        """
        self.cluster = cluster
        self.context_sharing_ratio = context_sharing_ratio
        self.seed = seed
        
        self.workload_gen = WorkloadGenerator(context_sharing_ratio, seed)
    
    async def run_baseline_simulation(
        self,
        num_requests: int
    ) -> Tuple[SystemMetrics, List[dict]]:
        """
        Run simulation with baseline scheduler.
        
        Args:
            num_requests: Number of requests to process
            
        Returns:
            Tuple of (final metrics, decision log)
        """
        scheduler = BaselineScheduler()
        decisions = []
        
        # Reset cluster state
        await self._reset_cluster()
        
        for i in range(num_requests):
            request = self.workload_gen.generate_request()
            metrics = self.cluster.get_all_metrics()
            
            workload_size = request.estimate_workload_size()
            decision = scheduler.select_gpu(
                gpus=metrics,
                workload_size=workload_size,
                context_id=None,  # Baseline doesn't use context
                request_id=request.request_id
            )
            
            # Update GPU state
            vram_increase = 0.1 if i % 10 == 0 else 0  # Occasional VRAM increase
            util_increase = 2 if i % 5 == 0 else 0
            
            self.cluster.update_gpu_workload(
                decision.selected_gpu,
                util_increase,
                vram_increase
            )
            
            # Simulate thermal effects
            self.cluster.simulate_workload_tick()
            
            decisions.append({
                "request_id": request.request_id,
                "gpu": decision.selected_gpu,
                "temp": decision.temperature,
                "context_reused": False
            })
            
            self.cluster.request_count += 1
        
        return self.cluster.get_system_metrics(), decisions
    
    async def run_thermocache_simulation(
        self,
        num_requests: int
    ) -> Tuple[SystemMetrics, List[dict]]:
        """
        Run simulation with ThermoCache scheduler.
        
        Args:
            num_requests: Number of requests to process
            
        Returns:
            Tuple of (final metrics, decision log)
        """
        context_cache = ContextCache()
        thermal_predictor = ThermalPredictor()
        scheduler = ThermalAwareScheduler(context_cache, thermal_predictor)
        decisions = []
        
        # Reset cluster state
        await self._reset_cluster()
        
        for i in range(num_requests):
            request = self.workload_gen.generate_request()
            metrics = self.cluster.get_all_metrics()
            
            # Register or reuse context
            ctx_metadata, is_new = await context_cache.register_or_reuse(
                content=request.context or request.prompt,
                gpu_location=0,  # Will be updated by scheduler
                context_id=request.context
            )
            
            workload_size = request.estimate_workload_size()
            decision = await scheduler.select_gpu(
                gpus=metrics,
                workload_size=workload_size,
                context_id=request.context,
                request_id=request.request_id
            )
            
            # Update context location
            if ctx_metadata.gpu_location != decision.selected_gpu:
                await context_cache.index.update_gpu_location(
                    request.context, decision.selected_gpu
                )
                self.cluster.add_context_to_gpu(
                    decision.selected_gpu,
                    request.context or "default",
                    0.1
                )
            
            # Update GPU state
            vram_increase = 0.05 if is_new else 0.01  # Less VRAM for reused context
            util_increase = 2 if i % 5 == 0 else 0
            
            self.cluster.update_gpu_workload(
                decision.selected_gpu,
                util_increase,
                vram_increase,
                contexts=[request.context] if request.context else []
            )
            
            # Update thermal predictor
            for m in metrics:
                thermal_predictor.update_gpu_temperature(m.gpu_id, m.temperature)
            
            # Simulate thermal effects
            self.cluster.simulate_workload_tick()
            
            decisions.append({
                "request_id": request.request_id,
                "gpu": decision.selected_gpu,
                "temp": decision.temperature,
                "context_reused": decision.context_reused,
                "score": decision.score
            })
            
            self.cluster.request_count += 1
        
        return self.cluster.get_system_metrics(context_cache), decisions
    
    async def _reset_cluster(self):
        """Reset cluster to initial state."""
        for gpu in self.cluster.gpus.values():
            gpu.temperature = gpu.base_temp
            gpu.utilization = 0
            gpu.vram_used = 0
            gpu.contexts = []
            gpu.workload_queue = []
        
        self.cluster.request_count = 0
        self.cluster.start_time = datetime.now()
        
        # Reset workload generator
        self.workload_gen = WorkloadGenerator(self.context_sharing_ratio, self.seed)
    
    async def run_comparison(
        self,
        num_requests: int = 1000
    ) -> dict:
        """
        Run full comparison between baseline and ThermoCache.
        
        Args:
            num_requests: Number of requests per simulation
            
        Returns:
            Comparison results dictionary
        """
        logger.info(f"Starting comparison simulation with {num_requests} requests")
        
        # Run baseline
        logger.info("Running baseline simulation...")
        baseline_metrics, baseline_decisions = await self.run_baseline_simulation(num_requests)
        
        # Run ThermoCache
        logger.info("Running ThermoCache simulation...")
        thermocache_metrics, thermocache_decisions = await self.run_thermocache_simulation(num_requests)
        
        # Calculate comparison metrics
        comparison = {
            "temperature_reduction": baseline_metrics.average_temperature - thermocache_metrics.average_temperature,
            "peak_temperature_reduction": baseline_metrics.peak_temperature - thermocache_metrics.peak_temperature,
            "vram_savings_percent": (
                (baseline_metrics.total_vram_used - thermocache_metrics.total_vram_used) 
                / baseline_metrics.total_vram_used * 100 
                if baseline_metrics.total_vram_used > 0 else 0
            ),
            "context_reuse_rate": thermocache_metrics.context_hit_rate,
            "thermal_distribution_improvement": self._calculate_thermal_distribution_improvement(
                baseline_decisions, thermocache_decisions
            )
        }
        
        return {
            "baseline": baseline_metrics,
            "thermocache": thermocache_metrics,
            "comparison": comparison,
            "baseline_decisions": baseline_decisions[:100],  # Sample
            "thermocache_decisions": thermocache_decisions[:100]
        }
    
    def _calculate_thermal_distribution_improvement(
        self,
        baseline_decisions: List[dict],
        thermocache_decisions: List[dict]
    ) -> float:
        """Calculate improvement in thermal distribution."""
        if not baseline_decisions or not thermocache_decisions:
            return 0.0
        
        baseline_temps = [d["temp"] for d in baseline_decisions]
        thermocache_temps = [d["temp"] for d in thermocache_decisions]
        
        # Lower variance = better distribution
        baseline_var = np.var(baseline_temps)
        thermocache_var = np.var(thermocache_temps)
        
        if baseline_var == 0:
            return 0.0
        
        return (baseline_var - thermocache_var) / baseline_var * 100
